# Generated by Django 5.1.15 on 2026-05-07 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('usuarios', '0002_alter_usuario_rol_docente_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_registro', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('qr', 'Solo QR'), ('facial', 'Solo Facial'), ('qr+facial', 'QR + Facial')], default='qr+facial', max_length=20)),
                ('face_verified', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cursos.sesion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sesion', 'estudiante'), name='unique_asistencia_por_sesion')],
            },
        ),
    ]
