from decouple import config

from .base import *

DEBUG = False
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", default="").split(",")

# Dokploy terminates TLS before requests reach the container. Trust its
# forwarded scheme so absolute URLs generated by Django remain HTTPS.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# The proxy may not preserve the original scheme on every request. Media URLs
# are consumed by the HTTPS frontend, so never serialize them as HTTP in prod.
FORCE_HTTPS_MEDIA_URLS = True

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
